# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Главная
email: 12312363432@mail.ru
description: >- # this means to ignore newlines until "baseurl:"
  Github:
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kep0cuh.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  KEP0CUH

# Build settings
theme: minima

plugins:
  - jekyll-feed 

gems:
  - jekyll-redirect-from

collections:
  opengl:
    output: true
    permalink: '/opengl/:path'
  cg:
    output: true
    permalink: '/cg/:path'
  ps1:
    output: true
    permalink: '/ps1/:path'
  sfml:
    output: true
    permalink: '/sfml/:path'
  js:
    output: true
    permalink: '/js/:path'
  compilers:
    output: true
    permalink: '/compilers/:path'
  os:
    output: true
    permalink: '/os/:path'
  os2:
    output: true
    permalink: '/os2/:path'
  cxx:
    output: true
    permalink: '/cxx/:path'
  resume:
    output: true
    permalink: '/resume/:path'
  resume2:
    output: true
    permalink: '/resume/pages/:path'

defaults:
    - scope:
        type: opengl
      values:
        layout: article
    - scope:
        type: cg
      values:
        layout: article
    - scope:
        type: ps1
      values:
        layout: article
    - scope:
        type: sfml
      values:
        layout: article
    - scope:
        type: js
      values:
        layout: article
    - scope:
        type: packman
      values:
        layout: article
    - scope:
        type: compilers
      values:
        layout: article
    - scope:
        type: os
      values:
        layout: article
    - scope:
        type: os2
      values:
        layout: article
    - scope:
        type: cxx
      values:
        layout: article
    - scope:
        type: resume
      values:
        layout: article
    - scope:
        type: pages
      values:
        layout: article
    - scope:
        type: resume2
      values:
        layout: article

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
